services:
  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  gym-web:
    build: .
    container_name: web-site-gym
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      migretion:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      redis:
        condition: service_started

    env_file: .env

  migretion:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  collectstatic:
    build: .
    command: python manage.py collectstatic --noinput
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file: .env

  celery-beat:
    build: .
    container_name: celery-beat-gym
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      migretion:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file: .env

  celery-work:
    build: .
    container_name: celery-work-gym
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      migretion:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file: .env

  nginx:
    image: nginx:alpine
    container_name: nginx_gym
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      - frontend_dist:/app/frontend:ro
    depends_on:
      gym-web:
        condition: service_started
      collectstatic:
        condition: service_completed_successfully
      frontend-builder:
        condition: service_completed_successfully

  frontend-builder:
    build: ../gym-frontend
    volumes:
      - frontend_dist:/app/dist

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  frontend_dist: