# Generated by Django 5.2.13 on 2026-06-13 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_plan', models.CharField(choices=[('mensal', 'Trimestal'), ('trimestal', 'Trimestral'), ('anual', 'Anual')], default='pendente', max_length=15)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='pendente', max_length=15)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('expected_payment', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
