# Generated by Django 5.2.13 on 2026-06-13 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='expected_payment',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
