# Generated by Django 5.2.13 on 2026-06-18 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='expected_payment',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
