# Generated by Django 5.2.13 on 2026-06-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_canceledplans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='status',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
