# Generated by Django 5.2.13 on 2026-06-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_remove_plan_status_plan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CanceledPlans',
        ),
    ]
