# Generated by Django 5.2.13 on 2026-06-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_plan_last_payment_delete_canceledplans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='last_payment',
        ),
        migrations.AddField(
            model_name='plan',
            name='payment_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
