# Generated by Django 5.2.13 on 2026-06-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_remove_plan_last_payment_plan_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Valido'),
        ),
    ]
